# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- chmod +x /Scripts/install.sh
- ./Scripts/install.sh
script:
- chmod +x /Scripts/build.sh
- ./Scripts/build.sh